---
title: "Data Cleaning"
author: "Eric Huang"
date: "11/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}  
# 2017-18 data

# Loading 2017-18 capacity/occupancy sheets
library("readxl")

sheets <- excel_sheets("~/Desktop/roomselection/1718cap_occup.xlsx")
sheetList <- lapply(sheets, 
                    function(x)read_excel("~/Desktop/roomselection/1718cap_occup.xlsx",
                                          range = "A1:P30",
                                          sheet = x))

names(sheetList) <- sheets

# Selecting upperclass houses (rows)
uc_houses_num <- c(2,3,5,7,8,9,11,13,15,16,18,20,21,23,24,25,26,27,29)
sheetNames <- names(sheetList)
uc_list <- list()
for (i in 1:length(sheetNames)) {
  curr_sheet <- sheetList[[sheetNames[i]]]
  if (curr_sheet[21,1] == "Stever House"){
    uc_houses_num <- c(2,3,5,7,8,9,11,13,15,16,18,20,22,23,24,25,26,27)
  } else {
    uc_houses_num <- c(2,3,5,7,8,9,11,13,15,16,18,20,21,23,24,25,26,27)
  }
  
  cleaned_sheet <- curr_sheet[uc_houses_num,]
  uc_list[[i]] = cleaned_sheet
}
names(uc_list) <- sheets
list2env(uc_list,.GlobalEnv)

# Selecting upperclass occupancy/vacancy variables (columns)
sheetNames <- names(uc_list)
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list[[sheetNames[i]]]
  cleaned_sheet <- curr_sheet[c(1,4,8,12)]
  uc_list[[i]] = cleaned_sheet
}

names(uc_list) <- sheets
list2env(uc_list,.GlobalEnv)

# Computing column totals
sheetNames <- names(uc_list)
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list[[sheetNames[i]]]
  cleaned_sheet <- rbind(curr_sheet, c("Total", colSums(curr_sheet[-1])))
  colnames(cleaned_sheet) <- c("Building", "Capacity (in beds)", "Actual Occupancy", "Vacancy")
  uc_list[[i]] = cleaned_sheet
}

names(uc_list) <- sheets
list2env(uc_list,.GlobalEnv)

# Editing row name wording
sheetNames <- names(uc_list)
# may need to run loop twice for *both* 'Spirit' *and* '5170 MM' to come up
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list[[sheetNames[i]]]
  cleaned_sheet <- curr_sheet
  if (curr_sheet[12,1] == "Spirit House/Roselawn 15"){
    cleaned_sheet[12,1] = "Spirit House"
  } else if (curr_sheet[13,1] == "Spirit House/5170 MM"){
    cleaned_sheet[13,1] = "5170 MM"
  } 
  uc_list[[i]] = cleaned_sheet
}

names(uc_list) <- sheets
list2env(uc_list,.GlobalEnv)

# Adjusting 'Building' order
sheetNames <- names(uc_list)
house_order <- c("Clyde House",
                 "Doherty Apartments",
                 "Fairfax Apartments",
                 "Henderson House",
                 "The Highlands Apts.",
                 "Margaret Morrison Apts",
                 "McGill House",
                 "Morewood Gardens",
                 "Neville Apartments",
                 "Resnik House",
                 "Roselawn Houses",
                 "Shady Oak Apartments",
                 "Spirit House",
                 "Webster Apartments",
                 "Welch House",
                 "West Wing",
                 "Woodlawn Apartments",
                 "5170 MM",
                 "Total")

for (i in 1:length(sheetNames)){
  sheet <- uc_list[[sheetNames[i]]]
  sheet <- sheet[match(house_order, sheet$Building),]
  uc_list[[i]] = sheet 
}

names(uc_list)
list2env(uc_list,.GlobalEnv)

# removing NA row from 'Original - 10-26-16' sheet
uc_list$`Original - 10-26-16` <- uc_list$`Original - 10-26-16`[c(1:17,19),]
names(uc_list)
list2env(uc_list,.GlobalEnv)

# reodering 'Original - 10-26-16' from position 1 to position 62
uc_list <- c(uc_list[-1],uc_list[1])
names(uc_list)
list2env(uc_list,.GlobalEnv)

# removing inaccurate "total" row from 'Original - 10-26-16' sheet
uc_list[[62]] <- uc_list[[62]][-c(18),]
curr_sheet <- uc_list[[62]]
names(uc_list)
list2env(uc_list,.GlobalEnv)

# recalculating "total" for 'Original - 10-26-16' sheet
curr_sheet <- uc_list[[62]]
curr_sheet2 = curr_sheet[[1]]
curr_sheet2 = as.data.frame(matrix(nrow=length(curr_sheet2), ncol=4))
curr_sheet2$Building = curr_sheet[[1]]
curr_sheet2$Capacity = as.numeric(curr_sheet[[2]])
curr_sheet2$Occ = as.numeric(curr_sheet[[3]])
curr_sheet2$Vac = as.numeric(curr_sheet[[4]])
  
curr_sheet2 = curr_sheet2[,-(1:4)]
colnames(curr_sheet2) = colnames(curr_sheet)
cleaned_sheet <- rbind(curr_sheet, c("Total", colSums(curr_sheet2[-1])))
uc_list[[62]] = cleaned_sheet

names(uc_list)
list2env(uc_list,.GlobalEnv)

# reorder dataframes by chronological order
library(rlist)
uc_list <- list.reverse(uc_list)
names(uc_list)
list2env(uc_list,.GlobalEnv)

```

```{r}
# 2018-19 data

# Loading 2018-19 capacity/occupancy sheets
sheets1 <- excel_sheets("~/Desktop/roomselection/1819cap_occup.xlsx")
sheetList1 <- lapply(sheets1, 
                    function(x)read_excel("~/Desktop/roomselection/1819cap_occup.xlsx",
                                          range = "A1:P30",
                                          sheet = x))
names(sheetList1) <- sheets1

# Selecting upperclass houses (rows)
sheetNames <- names(sheetList1)
uc_list1 <- list()
for (i in 1:length(sheetNames)) {
  curr_sheet <- sheetList1[[sheetNames[i]]]
  if (curr_sheet[17,1] == "Scobell House"){
    uc_houses_num <- c(2,3,5,7,8,9,11,13,15,16,18,20,21,23,24,25,26,27)
  } else {
    uc_houses_num <- c(2,3,5,7,8,9,10,12,14,16,17,18,20,22,24,25,26,27)
  }
  cleaned_sheet <- curr_sheet[uc_houses_num,]
  uc_list1[[i]] = cleaned_sheet
}

names(uc_list1) <- sheets1
list2env(uc_list1,.GlobalEnv)

# Selecting upperclass occupancy/vacancy variables (columns)
sheetNames <- names(uc_list1)
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list1[[sheetNames[i]]]
  cleaned_sheet <- curr_sheet[c(1,4,8,12)]
  uc_list1[[i]] = cleaned_sheet
}

names(uc_list1) <- sheets1
list2env(uc_list1,.GlobalEnv)

# Computing column totals
sheetNames <- names(uc_list1)
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list1[[sheetNames[i]]]
  
  curr_sheet2 = curr_sheet[[1]]
  curr_sheet2 = as.data.frame(matrix(nrow=length(curr_sheet2), ncol=4))
  curr_sheet2$Building = curr_sheet[[1]]
  curr_sheet2$Capacity = as.numeric(curr_sheet[[2]])
  curr_sheet2$Occ = as.numeric(curr_sheet[[3]])
  curr_sheet2$Vac = as.numeric(curr_sheet[[4]])
  
  curr_sheet2 = curr_sheet2[,-(1:4)]
  colnames(curr_sheet2) = colnames(curr_sheet)
  
  cleaned_sheet <- rbind(curr_sheet, c("Total", colSums(curr_sheet2[-1])))
  colnames(cleaned_sheet) <- c("Building", "Capacity (in beds)", "Actual Occupancy", "Vacancy")
  uc_list1[[i]] = cleaned_sheet
}

names(uc_list1) <- sheets1
list2env(uc_list1,.GlobalEnv)

# Editing row name wording
sheetNames <- names(uc_list1)
# may need to run loop twice for *both* 'Spirit' *and* '5170 MM' to come up
for (i in 1:length(sheetNames)){
  curr_sheet <- uc_list1[[sheetNames[i]]]
  cleaned_sheet <- curr_sheet
  if (curr_sheet[11,1] == "Roselawn 15/Old Spirit"){
    cleaned_sheet[11,1] = "Spirit House"
  } else if (curr_sheet[12,1] == "Spirit House/Roselawn 15"){
    cleaned_sheet[12,1] = "Spirit House"
  } else if (curr_sheet[14,1] == "Spirit House/5170 MM"){
    cleaned_sheet[14,1] = "5170 MM"
  } else if (curr_sheet[13,1] == "Spirit House/5170 MM"){
    cleaned_sheet[13,1] = "5170 MM"
  }
  uc_list1[[i]] = cleaned_sheet
}

names(uc_list1) <- sheets1
list2env(uc_list1,.GlobalEnv)

# Adjusting 'Building' order
sheetNames <- names(uc_list1)
house_order <- c("Clyde House",
                 "Doherty Apartments",
                 "Fairfax Apartments",
                 "Henderson House",
                 "The Highlands Apts.",
                 "Margaret Morrison Apts",
                 "McGill House",
                 "Morewood Gardens",
                 "Neville Apartments",
                 "Resnik House",
                 "Roselawn Houses",
                 "Shady Oak Apartments",
                 "Spirit House",
                 "Webster Apartments",
                 "Welch House",
                 "West Wing",
                 "Woodlawn Apartments",
                 "5170 MM",
                 "Total")

for (i in 1:length(sheetNames)){
  sheet <- uc_list1[[sheetNames[i]]]
  sheet <- sheet[match(house_order, sheet$Building),]
  uc_list1[[i]] = sheet 
}

names(uc_list1)
list2env(uc_list1,.GlobalEnv)

# removing '2-21-18(day1RS)' and '2-22-18(day2RS)' sheets from general list
uc_list1 <- uc_list1[-c(51,52)]
names(uc_list1)
list2env(uc_list1,.GlobalEnv)

# create separate list for the "proposed" sheets
proposed_list <- uc_list1[c(50:55)]
names(proposed_list)
list2env(proposed_list,.GlobalEnv)

# removing "proposed" sheets from general list and reordering dataframes by chronological order
uc_list1 <- uc_list1[-c(50:55)]
uc_list1 <- list.reverse(uc_list1)
names(uc_list1)
list2env(uc_list1,.GlobalEnv)

```

```{r}
# 2017-18 data to excel
rename <- names(uc_list)

write.xlsx(uc_list[[rename[1]]], file="~/Desktop/roomselection/sheets/1.xlsx",
             sheetName="Original - 10-26-16", row.names=FALSE)
write.xlsx(uc_list[[rename[2]]], file="~/Desktop/roomselection/sheets/2.xlsx",
             sheetName="am2-24-17(end_ret)", row.names=FALSE)
write.xlsx(uc_list[[rename[3]]], file="~/Desktop/roomselection/sheets/3.xlsx",
             sheetName="am2-27-27(aft_day1PI)", row.names=FALSE)
write.xlsx(uc_list[[rename[4]]], file="~/Desktop/roomselection/sheets/4.xlsx",
             sheetName="am2-28-17(aft_day2PI)", row.names=FALSE)
write.xlsx(uc_list[[rename[5]]], file="~/Desktop/roomselection/sheets/5.xlsx",
             sheetName="3-1-17", row.names=FALSE)
write.xlsx(uc_list[[rename[6]]], file="~/Desktop/roomselection/sheets/6.xlsx",
             sheetName="am3-2-17(aft_day1BH)", row.names=FALSE)
write.xlsx(uc_list[[rename[7]]], file="~/Desktop/roomselection/sheets/7.xlsx",
             sheetName="am3-3-17(aft_day2BH)", row.names=FALSE)
write.xlsx(uc_list[[rename[8]]], file="~/Desktop/roomselection/sheets/8.xlsx",
             sheetName="am3-6-17(start_day1GS)", row.names=FALSE)
write.xlsx(uc_list[[rename[9]]], file="~/Desktop/roomselection/sheets/9.xlsx",
             sheetName="am3-6-17(aft_day1)", row.names=FALSE)
write.xlsx(uc_list[[rename[10]]], file="~/Desktop/roomselection/sheets/10.xlsx",
             sheetName="am3-7-17(start_day2)", row.names=FALSE)
write.xlsx(uc_list[[rename[11]]], file="~/Desktop/roomselection/sheets/11.xlsx",
             sheetName="pm3-7-17(aft_day2)", row.names=FALSE)
write.xlsx(uc_list[[rename[12]]], file="~/Desktop/roomselection/sheets/12.xlsx",
             sheetName="am3-8-17(aft_day2)", row.names=FALSE)
write.xlsx(uc_list[[rename[13]]], file="~/Desktop/roomselection/sheets/13.xlsx",
             sheetName="am3-9-17(aft_day3)", row.names=FALSE)
write.xlsx(uc_list[[rename[14]]], file="~/Desktop/roomselection/sheets/14.xlsx",
             sheetName="am3-10-17(aft_day4)", row.names=FALSE)
write.xlsx(uc_list[[rename[15]]], file="~/Desktop/roomselection/sheets/15.xlsx",
             sheetName="am3-13-17(aft_open_b4_canc)", row.names=FALSE)
write.xlsx(uc_list[[rename[16]]], file="~/Desktop/roomselection/sheets/16.xlsx",
             sheetName="3-15-17", row.names=FALSE)
write.xlsx(uc_list[[rename[17]]], file="~/Desktop/roomselection/sheets/17.xlsx",
             sheetName="4-6-17", row.names=FALSE)
write.xlsx(uc_list[[rename[18]]], file="~/Desktop/roomselection/sheets/18.xlsx",
             sheetName="4-10-17(aft_open_canc)", row.names=FALSE)
write.xlsx(uc_list[[rename[19]]], file="~/Desktop/roomselection/sheets/19.xlsx",
             sheetName="4-21-17", row.names=FALSE)
write.xlsx(uc_list[[rename[20]]], file="~/Desktop/roomselection/sheets/20.xlsx",
             sheetName="4-28-17", row.names=FALSE)
write.xlsx(uc_list[[rename[21]]], file="~/Desktop/roomselection/sheets/21.xlsx",
             sheetName="5-5-17", row.names=FALSE)
write.xlsx(uc_list[[rename[22]]], file="~/Desktop/roomselection/sheets/22.xlsx",
             sheetName="5-12-17", row.names=FALSE)
write.xlsx(uc_list[[rename[23]]], file="~/Desktop/roomselection/sheets/23.xlsx",
             sheetName="5-15-17", row.names=FALSE)
write.xlsx(uc_list[[rename[24]]], file="~/Desktop/roomselection/sheets/24.xlsx",
             sheetName="5-24-27", row.names=FALSE)
write.xlsx(uc_list[[rename[25]]], file="~/Desktop/roomselection/sheets/25.xlsx",
             sheetName="5-31-17", row.names=FALSE)
write.xlsx(uc_list[[rename[26]]], file="~/Desktop/roomselection/sheets/26.xlsx",
             sheetName="6-5-17", row.names=FALSE)
write.xlsx(uc_list[[rename[27]]], file="~/Desktop/roomselection/sheets/27.xlsx",
             sheetName="6-12-17", row.names=FALSE)
write.xlsx(uc_list[[rename[28]]], file="~/Desktop/roomselection/sheets/28.xlsx",
             sheetName="6-14-17", row.names=FALSE)
write.xlsx(uc_list[[rename[29]]], file="~/Desktop/roomselection/sheets/29.xlsx",
             sheetName="6-15-17", row.names=FALSE)
write.xlsx(uc_list[[rename[30]]], file="~/Desktop/roomselection/sheets/30.xlsx",
             sheetName="6-19-17", row.names=FALSE)
write.xlsx(uc_list[[rename[31]]], file="~/Desktop/roomselection/sheets/31.xlsx",
             sheetName="6-22-17", row.names=FALSE)
write.xlsx(uc_list[[rename[32]]], file="~/Desktop/roomselection/sheets/32.xlsx",
             sheetName="6-23-17", row.names=FALSE)
write.xlsx(uc_list[[rename[33]]], file="~/Desktop/roomselection/sheets/33.xlsx",
             sheetName="6-26-17", row.names=FALSE)
write.xlsx(uc_list[[rename[34]]], file="~/Desktop/roomselection/sheets/34.xlsx",
             sheetName="6-27-17", row.names=FALSE)
write.xlsx(uc_list[[rename[35]]], file="~/Desktop/roomselection/sheets/35.xlsx",
             sheetName="7-5-17", row.names=FALSE)
write.xlsx(uc_list[[rename[36]]], file="~/Desktop/roomselection/sheets/36.xlsx",
             sheetName="7-19-17", row.names=FALSE)
write.xlsx(uc_list[[rename[37]]], file="~/Desktop/roomselection/sheets/37.xlsx",
             sheetName="7-26-17", row.names=FALSE)
write.xlsx(uc_list[[rename[38]]], file="~/Desktop/roomselection/sheets/38.xlsx",
             sheetName="7-28-17", row.names=FALSE)
write.xlsx(uc_list[[rename[39]]], file="~/Desktop/roomselection/sheets/39.xlsx",
             sheetName="8-11-17", row.names=FALSE)
write.xlsx(uc_list[[rename[40]]], file="~/Desktop/roomselection/sheets/40.xlsx",
             sheetName="8-18-17", row.names=FALSE)
write.xlsx(uc_list[[rename[41]]], file="~/Desktop/roomselection/sheets/41.xlsx",
             sheetName="8-19-17 FY Opening", row.names=FALSE)
write.xlsx(uc_list[[rename[42]]], file="~/Desktop/roomselection/sheets/42.xlsx",
             sheetName="8-25-17", row.names=FALSE)
write.xlsx(uc_list[[rename[43]]], file="~/Desktop/roomselection/sheets/43.xlsx",
             sheetName="8-29-17", row.names=FALSE)
write.xlsx(uc_list[[rename[44]]], file="~/Desktop/roomselection/sheets/44.xlsx",
             sheetName="9-8-17", row.names=FALSE)
write.xlsx(uc_list[[rename[45]]], file="~/Desktop/roomselection/sheets/45.xlsx",
             sheetName="9-15-17", row.names=FALSE)
write.xlsx(uc_list[[rename[46]]], file="~/Desktop/roomselection/sheets/46.xlsx",
             sheetName="9-22-17", row.names=FALSE)
write.xlsx(uc_list[[rename[47]]], file="~/Desktop/roomselection/sheets/47.xlsx",
             sheetName="10-2-17 (Oct 1 Rpt)", row.names=FALSE)
write.xlsx(uc_list[[rename[48]]], file="~/Desktop/roomselection/sheets/48.xlsx",
             sheetName="10-13-17", row.names=FALSE)
write.xlsx(uc_list[[rename[49]]], file="~/Desktop/roomselection/sheets/49.xlsx",
             sheetName="10-20-17", row.names=FALSE)
write.xlsx(uc_list[[rename[50]]], file="~/Desktop/roomselection/sheets/50.xlsx",
             sheetName="10-27-17", row.names=FALSE)
write.xlsx(uc_list[[rename[51]]], file="~/Desktop/roomselection/sheets/51.xlsx",
             sheetName="11-10-17", row.names=FALSE)
write.xlsx(uc_list[[rename[52]]], file="~/Desktop/roomselection/sheets/52.xlsx",
             sheetName="11-17-17", row.names=FALSE)
write.xlsx(uc_list[[rename[53]]], file="~/Desktop/roomselection/sheets/53.xlsx",
             sheetName="12-1-17", row.names=FALSE)
write.xlsx(uc_list[[rename[54]]], file="~/Desktop/roomselection/sheets/54.xlsx",
             sheetName="1-5-18", row.names=FALSE)
write.xlsx(uc_list[[rename[55]]], file="~/Desktop/roomselection/sheets/55.xlsx",
             sheetName="1-12-18", row.names=FALSE)
write.xlsx(uc_list[[rename[56]]], file="~/Desktop/roomselection/sheets/56.xlsx",
             sheetName="1-19-18", row.names=FALSE)
write.xlsx(uc_list[[rename[57]]], file="~/Desktop/roomselection/sheets/57.xlsx",
             sheetName="1-26-18", row.names=FALSE)
write.xlsx(uc_list[[rename[58]]], file="~/Desktop/roomselection/sheets/58.xlsx",
             sheetName="2-1-18 Feb 1 Report", row.names=FALSE)
write.xlsx(uc_list[[rename[59]]], file="~/Desktop/roomselection/sheets/59.xlsx",
             sheetName="2-9-18", row.names=FALSE)
write.xlsx(uc_list[[rename[60]]], file="~/Desktop/roomselection/sheets/60.xlsx",
             sheetName="3-9-18", row.names=FALSE)
write.xlsx(uc_list[[rename[61]]], file="~/Desktop/roomselection/sheets/61.xlsx",
             sheetName="4-6-18", row.names=FALSE)
write.xlsx(uc_list[[rename[62]]], file="~/Desktop/roomselection/sheets/62.xlsx",
             sheetName="4-27-18", row.names=FALSE)
```

```{r}
# 2018-19 data to excel
renamed <- names(uc_list1)
library(openxlsx)

write.xlsx(uc_list1[[renamed[1]]], file="~/Desktop/roomselection/spreadsheets/1.xlsx",
             sheetName="fall2017base", row.names=FALSE)
write.xlsx(uc_list1[[renamed[2]]], file="~/Desktop/roomselection/spreadsheets/2.xlsx",
             sheetName="2-23-18(day2RS)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[3]]], file="~/Desktop/roomselection/spreadsheets/3.xlsx",
             sheetName="2-26-18(aft_ret_day1PI)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[4]]], file="~/Desktop/roomselection/spreadsheets/4.xlsx",
             sheetName="2-27-18(aft_day2PI)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[5]]], file="~/Desktop/roomselection/spreadsheets/5.xlsx",
             sheetName="2-28-18(aft_day2PI)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[6]]], file="~/Desktop/roomselection/spreadsheets/6.xlsx",
             sheetName="3-1-18(aft_day1BH)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[7]]], file="~/Desktop/roomselection/spreadsheets/7.xlsx",
             sheetName="3-2-18(aft_day2)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[8]]], file="~/Desktop/roomselection/spreadsheets/8.xlsx",
             sheetName="am3-5-18(day1GS)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[9]]], file="~/Desktop/roomselection/spreadsheets/9.xlsx",
             sheetName="am3-6-18(aft_day1)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[10]]], file="~/Desktop/roomselection/spreadsheets/10.xlsx",
             sheetName="am3-7-18(aft_day2)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[11]]], file="~/Desktop/roomselection/spreadsheets/11.xlsx",
             sheetName="am3-8-18(aft_day3)", row.names=FALSE)
write.xlsx(uc_list1[[renamed[12]]], file="~/Desktop/roomselection/spreadsheets/12.xlsx",
             sheetName="3-9-18 final stats", row.names=FALSE)
write.xlsx(uc_list1[[renamed[13]]], file="~/Desktop/roomselection/spreadsheets/13.xlsx",
             sheetName="3-16-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[14]]], file="~/Desktop/roomselection/spreadsheets/14.xlsx",
             sheetName="4-6-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[15]]], file="~/Desktop/roomselection/spreadsheets/15.xlsx",
             sheetName="4-13-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[16]]], file="~/Desktop/roomselection/spreadsheets/16.xlsx",
             sheetName="4-20-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[17]]], file="~/Desktop/roomselection/spreadsheets/17.xlsx",
             sheetName="4-27-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[18]]], file="~/Desktop/roomselection/spreadsheets/18.xlsx",
             sheetName="5-9-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[19]]], file="~/Desktop/roomselection/spreadsheets/19.xlsx",
             sheetName="5-18-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[20]]], file="~/Desktop/roomselection/spreadsheets/20.xlsx",
             sheetName="5-23-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[21]]], file="~/Desktop/roomselection/spreadsheets/21.xlsx",
             sheetName="6-1-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[22]]], file="~/Desktop/roomselection/spreadsheets/22.xlsx",
             sheetName="6-8-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[23]]], file="~/Desktop/roomselection/spreadsheets/23.xlsx",
             sheetName="6-15-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[24]]], file="~/Desktop/roomselection/spreadsheets/24.xlsx",
             sheetName="6-18-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[25]]], file="~/Desktop/roomselection/spreadsheets/25.xlsx",
             sheetName="6-22-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[26]]], file="~/Desktop/roomselection/spreadsheets/26.xlsx",
             sheetName="6-29-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[27]]], file="~/Desktop/roomselection/spreadsheets/27.xlsx",
             sheetName="7-6-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[28]]], file="~/Desktop/roomselection/spreadsheets/28.xlsx",
             sheetName="7-13-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[29]]], file="~/Desktop/roomselection/spreadsheets/29.xlsx",
             sheetName="7-20-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[30]]], file="~/Desktop/roomselection/spreadsheets/30.xlsx",
             sheetName="7-24-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[31]]], file="~/Desktop/roomselection/spreadsheets/31.xlsx",
             sheetName="7-27-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[32]]], file="~/Desktop/roomselection/spreadsheets/32.xlsx",
             sheetName="7-31-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[33]]], file="~/Desktop/roomselection/spreadsheets/33.xlsx",
             sheetName="8-3-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[34]]], file="~/Desktop/roomselection/spreadsheets/34.xlsx",
             sheetName="8-10-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[35]]], file="~/Desktop/roomselection/spreadsheets/35.xlsx",
             sheetName="8-17-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[36]]], file="~/Desktop/roomselection/spreadsheets/36.xlsx",
             sheetName="8-18-18 FY Opening", row.names=FALSE)
write.xlsx(uc_list1[[renamed[37]]], file="~/Desktop/roomselection/spreadsheets/37.xlsx",
             sheetName="8-24-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[38]]], file="~/Desktop/roomselection/spreadsheets/38.xlsx",
             sheetName="8-31-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[39]]], file="~/Desktop/roomselection/spreadsheets/39.xlsx",
             sheetName="9-7-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[40]]], file="~/Desktop/roomselection/spreadsheets/40.xlsx",
             sheetName="9-14-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[41]]], file="~/Desktop/roomselection/spreadsheets/41.xlsx",
             sheetName="9-21-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[42]]], file="~/Desktop/roomselection/spreadsheets/42.xlsx",
             sheetName="9-28-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[43]]], file="~/Desktop/roomselection/spreadsheets/43.xlsx",
             sheetName="10-1-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[44]]], file="~/Desktop/roomselection/spreadsheets/44.xlsx",
             sheetName="10-5-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[45]]], file="~/Desktop/roomselection/spreadsheets/45.xlsx",
             sheetName="10-12-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[46]]], file="~/Desktop/roomselection/spreadsheets/46.xlsx",
             sheetName="10-19-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[47]]], file="~/Desktop/roomselection/spreadsheets/47.xlsx",
             sheetName="10-26-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[48]]], file="~/Desktop/roomselection/spreadsheets/48.xlsx",
             sheetName="11-2-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[49]]], file="~/Desktop/roomselection/spreadsheets/49.xlsx",
             sheetName="11-9-18", row.names=FALSE)
write.xlsx(uc_list1[[renamed[50]]], file="~/Desktop/roomselection/spreadsheets/50.xlsx",
             sheetName="11-16-18", row.names=FALSE)

```




